#### Site settings
title: Josh Rabinowitz
email: jrabinowitz2@gmail.com
author: Josh Rabinowitz
description:


###User specific content
primarylinks:
 - title: Github
   url: https://github.com/jrabinowitz2
 - title: LinkedIn
   url: https://www.linkedin.com/in/josh-rabinowitz-915705158
 - title: Handshake
   url: https://depaul.joinhandshake.com/users/3344898

skills:
 - Assembly
 - C
 - Python
 - Linux
 - Pentesting
 - Network Security
 - Malware Analysis
 - Reverse Engineeering
 - Web Dev

certs:
 - name: CCENT
   association: CISCO
 - name: G Suite Administrator
   association: Google

education:
 - school: DePaul University
   level: Bachelor of Science (B.Sc.)
   date: 2016-2019
   subject: Cybersecurity
   courses:
      course1
      course2
      course3
 - school: University of Illinois
   level: (None :/) 
   date: 2012-2016
   subject: Electrical Engineering
   courses:
      courseA
      courseB
      courseC

github:
 - jrabinowitz2/jrabinowitz2.github.io
 - jrabinowitz2/-Upcoming-Project-

####Build settings
permalink: :title/
kramdown:
   input: GFM
   parse_block_html: true
sass:
  sass_dir: css
