#### Site settings
title: Josh Rabinowitz
email: jrabinowitz2@gmail.com
author: Josh Rabinowitz
description:


###User specific content
primarylinks:
 - title: Github
   url: https://github.com/jrabinowitz2
 - title: LinkedIn
   url: https://www.linkedin.com/in/josh-rabinowitz-915705158
 - title: Handshake
   url: https://depaul.joinhandshake.com/users/3344898

skills:
 - Consulting
 - Pentesting
 - Enterprise Network Design/Security
 - Malware Analysis
 - Reverse-Engineeering
 - Web Dev
 - Malware Removal

technologies:
 - Assembly
 - C/C++
 - Python
 - SQL
 - Linux
 - Git
 - Apache
 - RoR
 - Bootstrap
 - Jekyll
 - Arduino
 - Hardware
 - IDA Pro
 - VMWare
 - OllyDGB
 - CISCO

certs:
 - name: CCENT
   association: CISCO
 - name: G Suite Administrator
   association: Google

education:
 - school: DePaul University
   level: B.S.
   date: Spring 2019
   subject: Cybersecurity
   logo: depaul.png
   logo_size: 30
   courses:
    - course1
    - course2
    - course3
 - school: University of Illinois
   level: B.S. 
   date: "-"
   subject: Electrical Engineering
   logo: uiuc.png
   logo_size: 30
   courses:
    - courseA
    - courseB
    - courseC

github:
 - jrabinowitz2/jrabinowitz2.github.io
 - jrabinowitz2/-Upcoming-Project-

####Build settings
permalink: :title/
kramdown:
   input: GFM
   parse_block_html: true
sass:
  sass_dir: css
