#### Site settings
title: Josh Rabinowitz
email: jrabinowitz2@gmail.com
author: Josh Rabinowitz
description:


###User specific content
primarylinks:
 - title: GitHub
   url: https://github.com/jrabinowitz2
   logo: github.png
   logo_size: 30
 - title: LinkedIn
   url: https://www.linkedin.com/in/josh-rabinowitz-915705158
   logo: linkedIn.png
   logo_size: 30
 - title: Handshake
   url: https://depaul.joinhandshake.com/users/3344898
   logo: handshake.png
   logo_size: 30

skills:
 - Consulting
 - Pentesting
 - Enterprise Network Design/Security
 - Malware Analysis
 - Reverse-Engineeering
 - Web Dev
 - Malware Removal
 - Technical Writing
 - Forensics

technologies:
 - Assembly
 - C/C++
 - Python
 - SQL
 - Linux
 - Git
 - Apache
 - Firewalls
 - RoR
 - Bootstrap
 - Jekyll
 - Arduino
 - Hardware
 - IDA Pro
 - VMWare
 - OllyDGB
 - CISCO

certs:
 - name: CCENT
   association: CISCO
 - name: G Suite Administrator
   association: Google

education:
 - school: DePaul University
   level: B.S.
   date: Spring 2019
   subject: Cybersecurity
   logo: depaul.png
   logo_size: 30
   courses:
    - Applied Networks and Security
    - Basic Communication Systems
    - Business/Professional Communication
    - Codes and Ciphers
    - Computer Systems II
    - Computer/Telecomm Systems
    - Data Structures in Java I, II
    - Digital Image Processing
    - Discrete Math I
    - Fundamentals of Info Assurance
    - Host Based Security
    - Intro to Databases
    - Intro to Local Area Networks
    - Intro to Web Computing
    - Issues in Information Security
    - Network Interconnection Technologies
    - Python for Programmers
    - Security Testing & Assessment
    - Telecommunication/Network Sec Practicum
    - Web Dev I
 - school: University of Illinois
   level: B.S. 
   date: "-"
   subject: Electrical Engineering
   logo: uiuc.png
   logo_size: 30
   courses:
    - Analog Signal Processing
    - Applied Linear Algebra
    - Calculus I, II, & III
    - Computer Systems & Programming
    - Differential Equations
    - Digital Signal Processing
    - Electromagnetic Fields & Waves I
    - Electronic Circuits Lab
    - Illinois Robotics in Space
    - Intro to Computer Eng
    - Intro to Computing Systems
    - Intro to Electrical/Computer Eng
    - Intro to Electronics
    - Microelectronic Circuits
    - Probability for Electrical/Computer Eng
    - Topics in Mathematics
    - University Physics&#58; Classical/Mechanics
    - University Physics&#58; Electrostatics & Magnetism
    - University Physics&#58; Quantum Mechanics
    - University Physics&#58; Thermodynamics

github:
 - jrabinowitz2/jrabinowitz2.github.io
 - jrabinowitz2/-Upcoming-Project-

####Build settings
permalink: :title/
kramdown:
   input: GFM
   parse_block_html: true
sass:
  sass_dir: css
